# Dockerfile.worker
FROM python:3.6-onbuild

# Create new user to keep Celery from complaining about being run as root.
RUN groupadd -r celery && useradd -r -g celery celery
USER celery

# Add flower to monitor the usage of workers
CMD ["celery", "flower", "-A", "proj", "--broker=amqp://celery:celery@localhost:5672//"]

# Start one worker to execute calculation
CMD ["celery", "-A", "worker:app", "worker", "--loglevel=INFO"]
